'use strict';
const questions = window.PAPER || [];
const $ = id => document.getElementById(id);
const STORE = 'mca-visual-practice-v1';
let saved = {};
try { saved = JSON.parse(localStorage.getItem(STORE) || '{}') || {}; } catch (_) { saved = {}; }
let current = 0, zoom = 1, activeToken = null, dragToken = null;
const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
function state(q) { return saved[q.id] || (saved[q.id] = { selected:[], fields:[], matches:[], points:{}, checked:false }); }
function persist() { try { localStorage.setItem(STORE, JSON.stringify(saved)); } catch (_) {} }
function same(a,b) { return JSON.stringify([...a].sort()) === JSON.stringify([...b].sort()); }
function node(tag, text, cls) { const e=document.createElement(tag); if(text!==undefined)e.textContent=text; if(cls)e.className=cls; return e; }
function button(text, onclick, cls) {const b=node('button',text,cls);b.type='button';b.onclick=onclick;return b;}
function nav(){const n=$('question-nav');n.replaceChildren();questions.forEach((q,i)=>{const b=button(String(q.id),()=>show(i),(i===current?'current ':'')+(saved[q.id]?.checked?'answered':''));b.title=q.title;n.append(b)});const done=Object.values(saved).filter(x=>x.checked).length;$('summary').textContent=`${done} of ${questions.length} attempted`;$('counter').textContent=`Question ${current+1} of ${questions.length}`;}
function show(i){current=Math.max(0,Math.min(questions.length-1,i));zoom=1;activeToken=null;dragToken=null;const q=questions[current],s=state(q);$('meta').textContent=`Question ${q.id} · Syllabus ${q.syllabus}`;$('title').textContent=q.title;$('prompt').textContent=q.prompt+(q.warning?'\n\nSource note: '+q.warning:'');$('context').hidden=!q.context;$('context').textContent=q.context||'';$('visual').hidden=!q.image;if(q.image){$('figure').src=q.image;$('figure').alt=`Figure for question ${q.id}`;applyZoom();}else $('figure').removeAttribute('src');const area=$('interaction');area.replaceChildren();$('answer-targets').replaceChildren();$('placed-tokens').replaceChildren();if(q.kind==='single'||q.kind==='multi')renderChoices(q,s,area);if(q.kind==='fields')renderFields(q,s,area);if(q.kind==='match')renderMatch(q,s,area);if(q.kind==='place')renderPlace(q,s,area);$('prev').disabled=current===0;$('next').disabled=current===questions.length-1;feedback(q,s);nav();history.replaceState(null,'',`#q${q.id}`);}
function renderChoices(q,s,area){const box=node('div',undefined,'choices');q.options.forEach((option,i)=>{const b=node('button',undefined,'choice'+(s.selected.includes(i)?' selected':''));b.type='button';b.append(node('span',alphabet[i]+'.','letter'),node('span',option));b.onclick=()=>{if(q.kind==='single')s.selected=[i];else s.selected=s.selected.includes(i)?s.selected.filter(x=>x!==i):[...s.selected,i];s.checked=false;persist();show(current)};box.append(b)});area.append(box);}
function renderFields(q,s,area){q.fields.forEach((f,i)=>{const box=node('div',undefined,'field');const label=node('label',f.label);box.append(label);if(f.choices){const sel=document.createElement('select');sel.append(new Option('Choose…',''));f.choices.forEach(x=>sel.append(new Option(x,x)));sel.value=s.fields[i]||'';sel.onchange=()=>{s.fields[i]=sel.value;s.checked=false;persist();feedback(q,s)};box.append(sel)}else{const inp=document.createElement('input');inp.type='text';inp.inputMode='decimal';inp.value=s.fields[i]||'';inp.placeholder='Enter answer';inp.oninput=()=>{s.fields[i]=inp.value;s.checked=false;persist();feedback(q,s)};box.append(inp)}area.append(box)});}
function renderMatch(q,s,area){q.terms.forEach((t,i)=>{const row=node('div',undefined,'match-row');row.append(node('strong',t));const sel=document.createElement('select');sel.append(new Option('Choose definition…',''));q.definitions.forEach((d,j)=>sel.append(new Option(d,String(j))));sel.value=s.matches[i]===undefined?'':String(s.matches[i]);sel.onchange=()=>{s.matches[i]=sel.value===''?undefined:Number(sel.value);s.checked=false;persist();feedback(q,s)};row.append(sel);area.append(row)});}
function renderPlace(q,s,area){const hint=node('p','Select a label, then click its location on the figure. Drag placed labels to adjust; click a placed label to remove it. Check to see the accepted regions in green.','hint');area.append(hint);const tray=node('div',undefined,'token-tray');q.tokens.forEach(t=>{const b=button(t,()=>{activeToken=t;tray.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x.textContent===t))},activeToken===t?'active':'');b.draggable=true;b.ondragstart=e=>{dragToken=t;e.dataTransfer.setData('text/plain',t)};tray.append(b)});area.append(tray);drawPoints(q,s);}
function drawPoints(q,s){const box=$('placed-tokens');box.replaceChildren();Object.entries(s.points||{}).forEach(([t,pos])=>{const b=button(t,e=>{e.stopPropagation();delete s.points[t];s.checked=false;persist();drawPoints(q,s);feedback(q,s)},'placed');b.style.left=`${pos[0]}%`;b.style.top=`${pos[1]}%`;b.draggable=true;b.ondragstart=e=>{dragToken=t;e.dataTransfer.setData('text/plain',t)};box.append(b)});drawTargets(q,s);}
function drawTargets(q,s){const box=$('answer-targets');box.replaceChildren();if(!s.checked||!q.targets)return;Object.entries(q.targets).forEach(([label,rect])=>{const pin=node('div',label,'answer-target');pin.style.left=`${rect[0]}%`;pin.style.top=`${rect[1]}%`;pin.style.width=`${rect[2]-rect[0]}%`;pin.style.height=`${rect[3]-rect[1]}%`;box.append(pin)});}
function placeAt(e){const q=questions[current];if(q.kind!=='place')return;const t=dragToken||activeToken;if(!t)return;const r=$('figure').getBoundingClientRect();const x=Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100));const y=Math.max(0,Math.min(100,(e.clientY-r.top)/r.height*100));const s=state(q);s.points[t]=[Math.round(x*10)/10,Math.round(y*10)/10];s.checked=false;dragToken=null;activeToken=null;persist();show(current);}
$('figure-viewport').addEventListener('click',placeAt);$('figure-viewport').addEventListener('dragover',e=>e.preventDefault());$('figure-viewport').addEventListener('drop',e=>{e.preventDefault();dragToken=e.dataTransfer.getData('text/plain');placeAt(e)});
function applyZoom(){const img=$('figure');const base=Math.min(img.naturalWidth||800,Math.max(320,$('figure-viewport').clientWidth-24));img.style.width=`${Math.round(base*zoom)}px`;img.style.maxWidth='none';$('zoom-label').textContent=`${Math.round(zoom*100)}%`;}function setZoom(v){zoom=Math.max(.5,Math.min(3,v));applyZoom();}
$('figure').onload=applyZoom;
$('zoom-in').onclick=()=>setZoom(zoom+.25);$('zoom-out').onclick=()=>setZoom(zoom-.25);$('zoom-reset').onclick=()=>setZoom(1);
function normalize(x){const value=String(x??'').trim().toLowerCase();return /^\d+(?:\.\d+)?$/.test(value)?String(Number(value)):value;}
function placementScore(q,s){return Object.entries(q.targets||{}).filter(([label,rect])=>{const pos=s.points?.[label];return pos&&pos[0]>=rect[0]&&pos[0]<=rect[2]&&pos[1]>=rect[1]&&pos[1]<=rect[3]}).length;}
function grade(q,s){if(q.kind==='single'||q.kind==='multi'){if(!q.answer)return null;return same(s.selected,q.answer)}if(q.kind==='fields'){if(!q.answers&&!q.fields.every(f=>f.answer))return null;const key=q.answers||q.fields.map(f=>f.answer);return key.every((v,i)=>normalize(s.fields[i])===normalize(v))}if(q.kind==='match')return q.answers.every((v,i)=>s.matches[i]===v);if(q.kind==='place')return q.targets?placementScore(q,s)===q.tokens.length:null;return null;}
function answerText(q,s){if(q.kind==='single'||q.kind==='multi')return q.answer?.map(i=>`${alphabet[i]}. ${q.options[i]}`).join('; ');if(q.kind==='fields')return (q.answers||q.fields.map(f=>f.answer)).filter(Boolean).join(' · ');if(q.kind==='match')return 'Match definitions in the displayed order (top to bottom).';if(q.kind==='place')return `${placementScore(q,s)} of ${q.tokens.length} labels in accepted regions; see the green boxes on the figure.`;return '';}
function feedback(q,s){const box=$('feedback');box.className='';if(!s.checked){box.textContent='';return;}const result=grade(q,s);if(result===null){box.className='review';box.textContent='Answer key unavailable.';}else if(result){box.textContent=`Correct. ${q.note||''}`;}else{box.className='wrong';box.textContent=`Not quite. Answer: ${answerText(q,s)}${q.note?' '+q.note:''}`;}}
$('check').onclick=()=>{const q=questions[current],s=state(q);s.checked=true;persist();if(q.kind==='place')drawTargets(q,s);feedback(q,s);nav();};$('prev').onclick=()=>show(current-1);$('next').onclick=()=>show(current+1);
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(e.key==='ArrowRight')show(current+1);if(e.key==='ArrowLeft')show(current-1)});
const start=Number((location.hash.match(/^#q(\d+)$/)||[])[1]||1);if(questions.length)show(start-1);
